{"uuid": "f2ddf5a9-3e90-423e-bcce-f40a7d4074fa", "children": ["ce7f0478-f72a-4d05-9818-52268c8091cc"], "befores": [{"name": "login_precondition", "status": "broken", "statusDetails": {"message": "AttributeError: 'ConfigReader' object has no attribute 'get_user_credentials'\n", "trace": "  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/venv/lib/python3.13/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/ducplm/Documents/auto_test/automation_project/tests/test_checkout.py\", line 16, in login_precondition\n    user_creds = config.get_user_credentials(\"standard_user\")\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1753550714747, "stop": 1753550714747}], "start": 1753550714747, "stop": 1753550714773}