{"name": "test_login_valid", "status": "failed", "statusDetails": {"message": "AssertionError: Đăng nhập thất bại: Không ở trang dashboard.\nassert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x103344490>()\n +    where <built-in method lower of str object at 0x103344490> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"05fe097f637a6479e15769a75972c69d\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"05fe097f637a6479e15769a75972c69d\")> = <tests.login_test.TestLoginWeb object at 0x1031d3110>.driver", "trace": "self = <tests.login_test.TestLoginWeb object at 0x1031d3110>\n\n    @allure.story(\"Valid Login\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_valid(self):\n        login_pg = LoginPage(self.driver)\n        login_pg.do_login(ConfigReader.get_username(), ConfigReader.get_password())\n>       assert \"dashboard\" in self.driver.current_url.lower(), \"Đăng nhập thất bại: Không ở trang dashboard.\"\nE       AssertionError: Đăng nhập thất bại: Không ở trang dashboard.\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x103344490>()\nE        +    where <built-in method lower of str object at 0x103344490> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"05fe097f637a6479e15769a75972c69d\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"05fe097f637a6479e15769a75972c69d\")> = <tests.login_test.TestLoginWeb object at 0x1031d3110>.driver\n\ntests/login_test.py:14: AssertionError"}, "attachments": [{"name": "Lỗi: test_login_valid_failure.png", "source": "bd285440-bf7f-4957-ae48-deb077c58cac-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "5f24ab90-654f-4fe5-8e1a-cf67fb909a7d-attachment.txt", "type": "text/plain"}], "start": 1753026342836, "stop": 1753026343721, "uuid": "2a5e7810-cad7-46a5-9879-bbd8f614ea08", "historyId": "3668f0babf23e581b9c79ac10463fa1b", "testCaseId": "3668f0babf23e581b9c79ac10463fa1b", "fullName": "tests.login_test.TestLoginWeb#test_login_valid", "labels": [{"name": "story", "value": "Valid Login"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginWeb"}, {"name": "host", "value": "DUCs-MacBook-Air.local"}, {"name": "thread", "value": "54439-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.login_test"}]}