{"name": "test_login_valid", "status": "broken", "statusDetails": {"message": "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method", "trace": "self = <Tests.login_test.TestLoginWeb object at 0x102fe11d0>\n\n    @allure.story(\"Valid Login\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_login_valid(self):\n        login_pg = LoginPage(self.driver)\n>       login_pg.do_login(ConfigReader.get_username(), ConfigReader.get_password())\n\nTests/login_test.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages/login_page.py:46: in do_login\n    self.click_login()\nPages/login_page.py:29: in click_login\n    self.click(self.click_login)\nPages/base_page.py:15: in click\n    element = self.wait_for_element_clickable(locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nPages/base_page.py:33: in wait_for_element_clickable\n    return WebDriverWait(self.driver, self.timeout).until(EC.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nvenv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py:129: in until\n    value = method(self._driver)\n            ^^^^^^^^^^^^^^^^^^^^\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ad4912cd6541129d90f8d9da172500eb\")>\n\n    def _predicate(driver: WebDriverOrWebElement):\n        target = mark\n        if not isinstance(target, WebElement):  # if given locator instead of WebElement\n>           target = driver.find_element(*target)  # grab element at locator\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not method\n\nvenv/lib/python3.13/site-packages/selenium/webdriver/support/expected_conditions.py:624: TypeError"}, "start": 1751982596527, "stop": 1751982599138, "uuid": "d3c044eb-a88c-4484-8ad9-e4de4b9363f6", "historyId": "8a24b95e892dcc639d8c68ef0eb9f6d0", "testCaseId": "8a24b95e892dcc639d8c68ef0eb9f6d0", "fullName": "Tests.login_test.TestLoginWeb#test_login_valid", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Valid Login"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLoginWeb"}, {"name": "host", "value": "DUCs-MacBook-Air.local"}, {"name": "thread", "value": "8163-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_test"}]}